name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version increment type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: xlf-editor/package-lock.json
    
    - name: Install dependencies
      run: |
        cd xlf-editor
        npm ci
      
    - name: Lint
      run: |
        cd xlf-editor
        npm run lint
      
    - name: Compile
      run: |
        cd xlf-editor
        npm run compile

    - name: Setup Git
      if: github.event_name == 'workflow_dispatch' && matrix.os == 'ubuntu-latest' && matrix.node-version == '18.x'
      run: |
        cd xlf-editor
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Bump Version
      if: github.event_name == 'workflow_dispatch' && matrix.os == 'ubuntu-latest' && matrix.node-version == '18.x'
      run: |
        cd xlf-editor
        npm version ${{ github.event.inputs.version_type }} --no-git-tag-version

    - name: Commit version bump
      if: github.event_name == 'workflow_dispatch' && matrix.os == 'ubuntu-latest' && matrix.node-version == '18.x'
      run: |
        cd xlf-editor
        git add package.json package-lock.json
        git commit -m "Bump version to $(node -p "require('./package.json').version") [skip ci]"
        git push

    - name: Auto-Increment Version and Package Extension
      if: github.event_name == 'workflow_dispatch' && matrix.os == 'ubuntu-latest' && matrix.node-version == '18.x'
      run: |
        cd xlf-editor
        npm install -g @vscode/vsce
        vsce package
        echo "NEW_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

    - name: Create GitHub Release
      if: github.event_name == 'workflow_dispatch' && matrix.os == 'ubuntu-latest' && matrix.node-version == '18.x'
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.NEW_VERSION }}
        name: Release v${{ env.NEW_VERSION }}
        files: "xlf-editor/*.vsix"
        draft: false
        prerelease: false
        generate_release_notes: true
